name: Check OpenSSL version

on:
  workflow_dispatch:
    inputs:
      openssl_version:
        description: 'The expected version of OpenSSL'
        required: true
        type: string


jobs:
  check_openssl_version_windows:
    runs-on: windows-latest
    steps:
      - name: Setup msys2 and OpenSSL
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          release: false
          install: mingw-w64-x86_64-openssl
      - name: Print OpenSSL version
        shell: msys2 {0}
        run: |
          openssl version -a
      - name: Check version
        shell: msys2 {0}
        run: |
          [ `openssl version -v | cut -d ' ' -f 2` == "${{ github.event.inputs.openssl_version }}" ]

  check_openssl_version_macos:
    strategy:
      matrix:
        platform: [macos-latest, macOS-10.15]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install OpenSSL
        run: |
          brew update
          brew install openssl@1.1
          brew upgrade openssl@1.1
      - name: Print OpenSSL version
        run: |
          openssl version -a
      - name: Check version
        run: |
          [ `openssl version -v | cut -d ' ' -f 2` == "${{ github.event.inputs.openssl_version }}" ]

