name: Check OpenSSL version

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:


jobs:
  print:
    name: "Print"
    runs-on: ubuntu-20.04
    steps:
      - name: "Print"
        run: |
          echo github.ref ${{ github.ref }}
          echo github.ref_name ${{ github.ref_name }}
          echo github.head_ref || github.sha  {{ github.head_ref || github.sha }}
