name: Check OpenSSL version

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:


jobs:
  print:
    - name: print
      run: |
        echo github.ref ${{ github.ref }}
        echo github.ref_name ${{ github.ref_name }}
