name: CI

on:
  workflow_dispatch:
    inputs:
      openssl_version:
        description: 'The expected version of OpenSSL'
        required: true
        type: string


jobs:
  check_openssl_version_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - { mingw: "64", msys: x86_64, python: "x64" }
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW${{ matrix.arch.mingw }}
          update: true
          release: false
          install: mingw-w64-${{ matrix.arch.msys }}-openssl
      - shell: msys2 {0}
        run: |
          [ `openssl version -v | cut -d ' ' -f 2` == "${{ inputs.openssl_version }}" ]

  check_openssl_version_macos:
    strategy:
      matrix:
        platform: [macos-latest, macos-10.15]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install OpenSSL
        run: |
          brew install openssl@1.1
      - name: Check version
        run: |
          [ `openssl version -v | cut -d ' ' -f 2` == "${{ inputs.openssl_version }}" ]

